// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdzI4_yfk2dCq1Hytutr1hoFQPfLxfm-k',
    appId: '1:110747729838:web:c182ce0ebc21101dd8923f',
    messagingSenderId: '110747729838',
    projectId: 'aquapro-b890e',
    authDomain: 'aquapro-b890e.firebaseapp.com',
    storageBucket: 'aquapro-b890e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBtKk8ApUZ3KjBStM4tWPZxLBlaLOGy8E',
    appId: '1:110747729838:android:f3a6ef05fa904cf6d8923f',
    messagingSenderId: '110747729838',
    projectId: 'aquapro-b890e',
    storageBucket: 'aquapro-b890e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvCMuUXptgJMw5DbSLJeaC_48uwz7U50E',
    appId: '1:110747729838:ios:05d7615d4f4286b3d8923f',
    messagingSenderId: '110747729838',
    projectId: 'aquapro-b890e',
    storageBucket: 'aquapro-b890e.appspot.com',
    iosBundleId: 'com.example.aquapro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvCMuUXptgJMw5DbSLJeaC_48uwz7U50E',
    appId: '1:110747729838:ios:061f0e40f6576816d8923f',
    messagingSenderId: '110747729838',
    projectId: 'aquapro-b890e',
    storageBucket: 'aquapro-b890e.appspot.com',
    iosBundleId: 'com.example.aquapro.RunnerTests',
  );
}
